### ISSUE TITLE
FIX: Homing after MANUAL_BED_LEVELING issue.

### ISSUE THREAD

**Issue by spaelectronics** [MarlinFirmware/MarlinDev#162]
I have been testing the latest MarlinDev (master) firmware, and I found an issue related to homing (G28) that only occurred after doing the "Manual / Mesh Bed Leveling" process.

**PROBLEM:**
When homing (G28), it would home to the endstops, then it would move the X & Y to 10 mm, which was displayed on the LCD correctly, but not in Repetier Host, which said the X & Y were at 0.

Secondly, the LCD stated that the Z-Axis was at 4mm, when it clearly was still at 0mm.

Long Story Short, after doing the bed leveling, G28 puts the hotend at 10,10 when it should be 0,0.

**Here is where the problem is in the code:**

**FILE: Marlin_main.cpp**

```
  // For manual leveling move back to 0,0
  #if ENABLED(MESH_BED_LEVELING)
    if (mbl_was_active) {
      current_position[X_AXIS] = mbl.get_x(0);
      current_position[Y_AXIS] = mbl.get_y(0);
      set_destination_to_current();
      feedrate = homing_feedrate[X_AXIS];
      line_to_destination();
      st_synchronize();
      current_position[Z_AXIS] = MESH_HOME_SEARCH_Z;
      sync_plan_position();
      mbl.active = 1;
      #if ENABLED(DEBUG_LEVELING_FEATURE)
        if (marlin_debug_flags & DEBUG_LEVELING) {
          print_xyz("mbl_was_active > current_position", current_position);
        }
      #endif
    }
  #endif
```

**Comment by eboston** [comment]
Why?  If the user needs the position, they can just send the M114 
command.  No need to force it on everyone whether they need it or not.

**Comment by drbogger** [comment]
Because when printing from Repetier Host, when it homes, it thinks its at 0 position, but when the print starts, it starts 10mm past where it should.

**Comment by eboston** [comment]
So how does sending the position back when you home effect anything?

**Comment by drbogger** [comment]
It lets repetier host know where it's at.

**Comment by eboston** [comment]
but you already said that Repeiter host thinks it at 0,0 so all you would be doing is telling it what it thinks.

**Comment by drbogger** [comment]
Your wrong. With manual_bed_leveling enabled, it homes, then immediately after it homes, it moves X & Y +10mm. But Repetier Host still thinks its at 0,0, when its actually at 10,10.

**Comment by eboston** [comment]
You stated, "When homing (G28), it would home to the endstops, then it would move the X & Y to 10 mm, which was displayed on the LCD correctly, but not in Repetier Host, which said the X & Y were at 0."  So at this point, Repetier thinks it is at 0,0 when the hot end is actually at 10, 10.

Your fix to manual leveling moves the hot end back to 0,0 where Repetier thinks it is, correct?  Or is it just resetting the home position from 0,0 to 10,10 in which case, that is totally wrong.

**Comment by drbogger** [comment]
it's just resetting  the home position to 10,10... but can you tell me how that is wrong?
Should I make the fix move back to 0,0 instead?

**Comment by eboston** [comment]
G28 is suppose to leave the hot end the home position, not somewhere else.  Normally this is at the min or max of the axis.  If G28 puts the hot end in one place before doing the manual bed leveling, and in a different place after, there is something wrong.  G28 should always put the hot end at the home location.  From looking at the Configuration.h file, it looks like it is leaving the hot end at one of the test points since by default, it tests 10mm in from each end of the axis.

Unless I am totally misunderstand how Manual/Mesh bed leveling is suppose to work.

**Comment by drbogger** [comment]
You are correct. G28 puts the hotend at the first test point. The code I posted above is what is causing it. Any idea why that code is even there to begin with? I am not very familiar with the coding of any type of auto leveling (or manual leveling in this case).

**Comment by eboston** [comment]
I'm not that familiar with the actual code so can't really help you there.

**Comment by drbogger** [comment]
Okay, I'll just leave it as a bug report for now. If I find a fix, I'll post it.

**Comment by thinkyhead** [comment]
@epatel Is this a bug? It kind of looks like it. At the end of manual leveling there's a `G28` command to re-home the printer. Then we have custom code (as shown above) within `gcode_G28` to set XY to the first mesh point, and Z to `MESH_HOME_SEARCH_Z`. But this code will actually affect homing whenever `mbl.active` is set to 1, not just during the leveling process. So it looks like this code just doesn't belong in `G28` and maybe some of it should be in your custom `G29` instead.

**Comment by epatel** [comment]
@thinkyhead I am happy to see someone actually testing it! :)

No, it is very intentional. The rational is that `G28` is made when one do not know the real position of the hotend. So while doing the `G28` it turns off the mesh calculations, then move to the closest best known measured position and turn the mesh calculations on. These steps I actually copied from another guy that did a manual bed levelling feature a couple years ago (doing it without the mesh that I added).

If its a big problem I can see if I can calculate the levelled `Z` for `[0,0]` and turn it on while in the homing position.

**Comment by thinkyhead** [comment]
@epatel Hmm, well you can see why moving the nozzle at the end of a `G28` operation is problematic. In this case Repetier Host is actually being presumptuous (since homing doesn't leave the position at 0,0,0 — it leaves the position set to the home position plus offsets) so that's not the main issue. The fact that the current Z position is being set to `MESH_HOME_SEARCH_Z` at the end of `G28` (when the nozzle is actually touching the bed, or may even be at the other end with a Z_MAX endstop) does seem to be a mistake.

You will note that for Automatic Bed Leveling there is a different behavior: `G28` completely turns off the leveling compensation. Also for Automatic Bed Leveling, no homing is done at the end. It just stays where it ends up after it puts the probe away, and then the very last thing that Automatic Bed Leveling `G29` does is to apply the rotation matrix to the current (raw, uncorrected) position so it becomes corrected. We might want to do that with MBL as well, to make it behave consistently with the way that ABL works. Since your MBL implementation saves its results it can be turned on/off any time. So you can still do a `G28` at the end (turning off MBL) but then enable it afterward, which will immediately apply the Z correction.

**Comment by epatel** [comment]
@thinkyhead If one has followed the instructions I wrote for the MBL the hotend should not touch the bed at `[0,0,0]`. This is a safety measure so one don't regularly run the hotend into the bed.

I hope you don't mean one should do the measuring every time after a `G28`? This is not automatic so its a little tedious. I maybe do it once per month or so (values being saved in EEPROM between usage).

Auto homing after a measure session is mainly for convenience. Sure the activation of MBL in `G28` can be separated but feels unnecessary as I guess it should be done every time and seperating it opens for forgetting it and can failed prints.

**Comment by drbogger** [comment]
The problem I was having, is that after a G28, it offsets the nozzle to 10,10, and it throws off repetier host, because it's assuming the nozzle is at 0,0.

Why exactly must the nozzle move after a G28? I'd much rather it stay at 0,0,0

**Comment by epatel** [comment]
@drbogger `G28` travels to the end stops. Having `X=0` and `Y=0` from there is fine but it isn't necessary for `Z` to be touching the bed at that point. Having the end stop for `Z` to be slightly above the bed makes it easy to setup and calibrate.

The movement to the closest best known measured point is to move to a known measured point and turn on the levelling calculations, it is a position where all the values are known. We have just reached the end stop and we have a measured point, activating levelling there is easy and safe. I could activate the levelling calculations at the end stops, but to do that I (think) will need to add a reverse calculation at `[0,0]` from the mesh, doable but will need testing etc. I can look into it, maybe add a final move to `[0,0,0]`.

**Comment by drbogger** [comment]
Adding a final move to '''' 0,0,0 '''' is fine by me. My biggest problem is it screws with repetier host thinking it's at '''' 0,0 '''' when in reality it's at '''' 10,10 ''''

**Comment by thinkyhead** [comment]
> I hope you don't mean one should do the measuring every time after a G28?

No that would be annoying. However, when MBL is turned on it shouldn't continue to have an effect on `G28`. I suggest that instead, if MBL is turned on during a `G28` turn it off temporarily, then just turn it back on when `G28` is all done. But without moving the nozzle away from `0,0,0`.

Meanwhile, it seems like a bug if Sean's machine thinks Z=4 when Z is actually touching the bed. It's this pair of lines at the end of `G28` that seems incorrect, but correct me if I'm misunderstanding. (I haven't actually tested MBL on my machine, but I guess I should!):
```cpp
current_position[Z_AXIS] = MESH_HOME_SEARCH_Z;
sync_plan_position();
```

**Comment by thinkyhead** [comment]
> BuildTak

I've not tried it, but I will in the future!

**Comment by drbogger** [comment]
So what is the suggested fix for this? Could this code be removed all together? Or is it required for something specific?

**Comment by epatel** [comment]
I guess the suggested fix is to calculate the real Z value at `[0.0]`. Activate the calculation and move to `Z=0` at the end of a `G28`. I'll see if I can add (and test) it this weekend.

**Comment by epatel** [comment]
Yeah, the code is needed at the moment. It's about turning on the calculations at a known point.

**Comment by drbogger** [comment]
Okay, I'll wait for your update.

**Comment by epatel** [comment]
Just created a PR. Actually this thing was easier than I thought. Hope it solves your problem.

**Comment by nitewing76** [comment]
@drbogger In the Repitier Host Printer Settings--->Printer Shape....is your X-Min, Y-Min, Bed Left, and Bed Front all set to 0? Having X/Y-Min=0 and Bed Front/Left=10 will cause the behavior.

This setting is confusing....because it has nothing to do with the dimensions of the structure supporting the bed, but the relative position of the nozzle to the bed after "G28 X Y".

I am assuming this discussion about Z=0, is only before the nozzle begins to heat up.  If not, then this a bad idea because in addition to the safety factor, there will be an transfer of heat from the nozzle to the bed. This means in the area where the nozzle is touching the bed, the bed will physically expand...then contract as that area of the bed cools while printing. Slightly changing the topology of the bed...the degree of which depends on the material of the bed and the coefficient of thermal expansion.

**Comment by thinkyhead** [comment]
I presume this issue is long fixed by now…?

**Comment by jbrazio** [comment]
@thinkyhead I would suggest to define a threshold and close "without questions" all issues not updated and not feature requests in the last couple of months. The code has change so much that they have lost their importance.

**Comment by thinkyhead** [comment]
I suppose you are right, João. Life is too short…

**Comment by brainscan** [comment]
@epatel just wondering if I undo these changes will mbl work again? Sorry Git really confuses me so I'm trying to work out how to put mbl back to its original state.

**Comment by epatel** [comment]
@brainscan Just for you I can see if I later today can setup my system again to do this fix for you. And you will be my tester, is that OK?

**Comment by brainscan** [comment]
That would be amazing!! Thank you so much. Happy to test, pretty sure if it can be reverted to the original code it will work perfectly, as it did from the start.

**Comment by epatel** [comment]
@brainscan Please try this https://github.com/epatel/Marlin/tree/marlin/g28_all_restpos

I added a new option `MESH_G28_REST_ORIGIN` which is off by default. Enabled it will move the nozzle to `Z` = 0 as requested by @spaelectronics 

Could you please test both cases that if enabled moves to Z=0 and not when off.

I based this on a commit before https://github.com/MarlinFirmware/Marlin/commit/bc5a547d55722a87d41d2e4ee6ad32ed9db736ba as I believe that commit broke MBL.

**Comment by gddeen** [comment]
Hmmm. When I do a 

    G29 S4 Z-0.3
    G28                 ; Homes XY, Probes [100,100,Z], Resets Z=Z-Probeoffsetfrom Nozzle-0.3,Homes Z, Sets Z=0

- Will your change add that BedZ (-0.3 in the case above) since there won't be a probe? I would assume not. (A few dozen G28s in a row wouldn't be too good.)  So, does that mean BEDZ can never be applied?

- Is there a G28 option to use the probe?

- Will M401 and M402 be in there??? (Raise/Lower the probe.)

**Comment by gddeen** [comment]
Never mind, I guess G28 will still do the probe. (A prior mesh bed level had G28 with no probe.)

**Comment by brainscan** [comment]
@epatel thank you, I will test tonight and report back.

**Comment by brainscan** [comment]
@epatel Success!! Works perfectly for both cases. The 0,0,0 setting seems to work fine for those that would want/need it that way. The original version works great and just as expected. 

Thank you so much!! I've not made a PR before so I will have to check out what to do.

**Comment by thinkyhead** [comment]
> If you want you may fork and make a PR for this into RCBugFix.

I can take care of that, no problem. If any issues introduced by https://github.com/MarlinFirmware/Marlin/commit/bc5a547d55722a87d41d2e4ee6ad32ed9db736ba still remain, this will be a good chance to debug them, as I will have access my 3D printer for a few hours.
