### ISSUE TITLE
@wackerbarth said

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/MarlinDev#172]
in another issue @wackerbarth commented - "First, let me thank you for the way that you are reporting the issue. You have given a reasonable description of the behavior and a reference to the exact version of the firmware that you are testing. I only wish that everyone would be so precise."

I would be delighted to use the build reference if I only knew where to find it.
The version # in "default_version.h" of what I dnld 9-12 is identical to what I dnld 8-6
Sorry to be clueless, but I have tried to find something else - please point it out.
thx

**Comment by Wackerbarth** [comment]
I guess the issue is in how you go about downloading the files.  If you use git, directly, `git describe` will tell you the latest commit and our USE_AUTOMATIC_VERSIONING can fill in the file.

However, github also offers the ability for someone to download a copy of just the files.(as a zip archive).
Unfortunately, unless we were to update the default_version.h, with every commit (WAY TOO MUCH EFFORT), we must leave it to the user to supply the information in that file which was current as of the time that the files were downloaded.  The default_version.h file is there for use by a vendor who might download a version from our repository, edit the Default_version.h file, customize the Configuration files to match his machine, and distribute all of those sources as a packaged archive.

If you are working from our repository on a regular basis, I strongly recommend that you use the `git` approach and enable automatic versioning.
